print("Hey! What's your name? ")
print()
myName = input("Your Name")
favFood = input("What is your favorite food? ")
favMusic = input("What is your favorite music? ")
location = input("Where do you live? ")
print("Hey")
print(myName)
print("I also LOVE")
print(favFood)
print("and")
print(favMusic)
print("and I live in")
print(location)
print("too!")
print("You are awesome at what you do!")
